#!/bin/bash
sudo luarocks install parallel
sudo luarocks install threads
sudo luarocks install sundown
sudo luarocks install cwrap
sudo luarocks install paths
sudo luarocks install graphicsmagick
sudo luarocks install torch
sudo luarocks install nn
sudo luarocks install nnx
sudo luarocks install torchx
sudo luarocks install cutorch
sudo luarocks install cunn
sudo luarocks install cunnx
sudo luarocks install dok
sudo luarocks install gnuplot
sudo luarocks install qtlua
sudo luarocks install qttorch
#sudo luarocks install lfs
sudo luarocks install penlight
sudo luarocks install sys
sudo luarocks install xlua
sudo luarocks install image
sudo luarocks install optim
sudo luarocks install cjson
sudo luarocks install trepl
sudo luarocks install nngraph
sudo luarocks install dpnn
sudo luarocks install dp
sudo luarocks install rnn
sudo luarocks install dataload
